### PR TITLE
fix: skip validation for server decompressed objects

### LINKED ISSUE #709: CONTENT_DOWNLOAD_MISMATCH with successful file download
#### Environment details
* OS: Windows 10 Pro 1809
* Node.js version: v10.15.3 LTS
* npm version: 6.4.1
* `@google-cloud/storage` version: 2.5.0

#### Steps to reproduce
0. Prepare a bucket with Cloud KMS Customer managed Key encryption. All files are private.
1. Upload an JPEG image file using: 
```javascript
function UploadFile() {
    storage.bucket("somebucket").upload("somefolder/someimage.jpg", {
        gzip: true,
        destination: "somefolder/someimage.jpg",
    }).then(results => {
        console.log("upload OK");
    })
    .catch(err => {
        console.error("Error: ", err);
    });
}
UploadFile()
// Upload works fine.
```
2. Try downloading the img file using: 
```javascript
function DownloadFile() {    
    const file = storage.bucket("somebucket").file("somefolder/someimage.jpg");
    
    file.download({
        destination: "someimage.jpg",
        // validation: false, // Why even disable validation?
    }).then(res => {
        console.log("DL OK");
    }).catch(err => {
        console.error(err); // Throws CONTENT_DOWNLOAD_MISMATCH
    })
}
DownloadFile()
```
3. ***Correct decompressed file is downloaded*** AND exception is thrown: `code=CONTENT_DOWNLOAD_MISMATCH message=The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again.`

I've read through [Issue 566](https://github.com/googleapis/nodejs-storage/issues/566), but seems like not a solution.

`storage.bucket("somebucket").file("somefolder/someimage.jpg").download({validation: false});` works, but there's no reason to or should disable validation.

To make sure if the hashes are actually a mismatch, I ran a local md5sum check on the downloaded and original image files.

```
$ md5sum downloaded.jpg original.jpg
a045a2e8e6b8d84aa8a319bcdba05419  downloaded.jpg
a045a2e8e6b8d84aa8a319bcdba05419  original.jpg
```

Downloaded file is a match to the original file.

BTW, This problem doesn't happen if the image is not gzipped on upload.

Thanks

### PR DESCRIPTION
**Pull request by jkwlui**
Fixes #709

### CODE REVIEW

**Comment by crwilcox** [comment]
Thanks @jkwlui . I am going to make a small tweak to the TODO and get CI Green

File: src/file.ts [hunk 1]
```diff
@@ -1369,6 +1370,17 @@ class File extends ServiceObject<File> {
 
         onCompleteCalled = true;
 
+        // TODO(https://github.com/googleapis/nodejs-storage/issues/709):
+        // Remove once the backend issue is fixed.
+        // If object is stored compressed (having metadata.contentEncoding === 'gzip')
+        // and was served decompressed, then skip checksum validation because the
+        // remote checksum is computed against the compressed version of the object.
+        if (this.metadata.contentEncoding === 'gzip' && !isServedCompressed) {
+          onCompleteCalled = true;
```
Comment (stephenplusplus) [inline src/file.ts]: I think this is already set above.

File: system-test/storage.ts [hunk 2]
```diff
@@ -2250,6 +2250,37 @@ describe('storage', () => {
...
+          gzip: true,
+        })
+        .then(() => {
+          tmp.setGracefulCleanup();
+          tmp.file((err, tmpFilePath) => {
+            assert.ifError(err);
+
+            const file = bucket.file(filename);
+            file
+              .createReadStream()
```
Comment (stephenplusplus) [inline system-test/storage.ts]: This needs an on-error handler.

File: system-test/storage.ts [hunk 3]
```diff
@@ -2250,6 +2250,37 @@ describe('storage', () => {
       });
     });
 
+    it('should skip validation if file is served decompressed', done => {
+      const filename = 'logo-gzipped.png';
+      bucket
+        .upload(FILES.logo.path, {
```
Comment (feywind) [inline system-test/storage.ts]: Re: style comments - the mix of promises and callbacks makes me twitch a bit. Actually the preferred way now is to use async/await, so you could make the lambda passed to it() async and then await on stuff. I think there's a promisify function we have handy for tmp?

Comment (bcoe) [reply system-test/storage.ts]: for unit tests, I'd be tempted to just use `mktempSync`, I don't know that we need a module for this:

https://nodejs.org/api/fs.html#fs_fs_mkdtempsync_prefix_options

I'd also consider switching to to `async`/`await`, would probably unravel this a bunch.

File: src/file.ts (hunk 1 above)
Comment (crwilcox) [reply src/file.ts]: Good catch.

File: system-test/storage.ts (hunk 2 above)
Comment (crwilcox) [reply system-test/storage.ts]: Different from the one on line 2269?

Comment (stephenplusplus) [reply system-test/storage.ts]: Yeah that one will catch errors from the write stream, but if the read stream has an error, it would go uncaught currently.

File: system-test/storage.ts (hunk 3 above)
Comment (jkwlui) [reply system-test/storage.ts]: Ended up using `tmp.fileSync()` since it's already there :)
Probably gonna require more boilerplate code if we'd switch to using `fs.mkdTempSync`.

File: system-test/storage.ts (hunk 2 above)
Comment (crwilcox) [reply system-test/storage.ts]: Looks like @jkwlui addressed this?
