### PR TITLE
fix: Determine `Content-Length` Before Attempting Multi-chunk Upload

### LINKED ISSUE #2073: Multi-chunk Upload Without `contentLength` Can Hang When `fileSize % chunkSize != 0`
A multi-chunk resumable upload hangs when the `chunkSize` is not evenly divisible by the file size when a `contentLength` is not provided.

ACs:
- Fix upload logic for this scenario
- Fix unit test(s)
- Add integration tests for the following scenarios:
  - `fileSize % chunkSize != 0`
  - `fileSize < chunkSize`

### PR DESCRIPTION
**Pull request by danielbankhead**
Fixes #2073  🦕

### CODE REVIEW

File: src/resumable-upload.ts [hunk 1]
```diff
@@ -718,13 +718,37 @@ export class Upload extends Writable {
...
+      // `- 1` as the ending byte is inclusive in the request.
+      const endingByte = bytesToUpload + this.numBytesWritten - 1;
+
+      // `Content-Length` for multiple chunk uploads is the size of the chunk,
+      // not the overall object
+      headers['Content-Length'] = bytesToUpload;
       headers[
         'Content-Range'
-      ] = `bytes ${this.offset}-${endingByte}/${this.contentLength}`;
+      ] = `bytes ${this.offset}-${endingByte}/${totalObjectSize}`;
```
Comment (frankyn) [inline src/resumable-upload.ts:751]: this def looks like a bug in that the content-length may not match the totalObjectSize; I'm guessing this is how this issue came up?

Comment (frankyn) [reply src/resumable-upload.ts:751]: Alternatively, you don't need to supply `totalObjectSize` and could instead use `*` and only use `totalObjectSize` once it's known to support streams of unknown byte length.

**Review by frankyn — CHANGES_REQUESTED** [review]

File: src/resumable-upload.ts (hunk 1 above)
Comment (danielbankhead) [reply src/resumable-upload.ts:751]: Unfortunately it errors when we use `*` on the final chunk in a multiple chunk transfer (see this commit https://github.com/googleapis/nodejs-storage/pull/2074/commits/53aa25dc69dd0304cdd8b8ae0bdd2dd6bf4d0fed). 

Which makes sense for 2 reasons:
- the final chunk could  be smaller than the minimum chunk size threshold ([256 KiB](https://cloud.google.com/storage/docs/performing-resumable-uploads#chunked-upload))
- it's unclear how the server would know this is the last chunk and we're done uploading

Comment (frankyn) [reply src/resumable-upload.ts:751]: Why not buffer up to multiple of 256kib?

Comment (danielbankhead) [reply src/resumable-upload.ts:751]: We do, using the user-provided `chunkSize` property. The last chunk in the upload maybe be less than that (e.g. uploading a 257KiB file in 256KiB chunks).

Comment (frankyn) [reply src/resumable-upload.ts:751]: interesting, I would expect the following:

Chunk 1: 256KiB
Chunk 2 (Also Finalize) 1KiB

Does this not work as expected or am I missing context?

Comment (danielbankhead) [reply src/resumable-upload.ts:751]: Unfortunately that does not work. The server doesn't know the 2nd chunk is the last chunk with `*` as the end range for multi-chunk uploads (single chunk upload is fine with `*`).

Comment (danielbankhead) [reply src/resumable-upload.ts:751]: See this error:
Screen Shot 2022-09-21 at 5 02 45 PM

Comment (frankyn) [reply src/resumable-upload.ts:751]: ah, I was saying you need to swap the `*` with the complete object size on the final chunk otherwise you'll get that error as expected.

**Review by frankyn — APPROVED** [review]
Discussed the implementation in detail with @danielbankhead.

The PR LGTM, it introduces not only unit tests but also system tests which validate critical multi chunk use cases which were not being tested before against the live service.

Complexity of resumable media API with streams caused the following use cases to not be captured: https://github.com/googleapis/nodejs-storage/pull/2074/commits/aa803746f63c0461b1c6fcbad690fb64554b94b5
The tests that failed in this commit now pass as expected.
