### PR TITLE
fix: retry multipart uploads on File.save()

### LINKED ISSUE #1281: Retry Strategy should be enabled by default for multipart uploads
1) Is this a client library issue or a product issue?
Library issue, that does not enable retries for multipart uploads and requires enabling retries automatically using `autoRetry: true`. Resumable uploads does support retries by default so there's an inconsistency here. I don't see any issue with enabling autoRetry by default for multipart uploads.

cc: @crwilcox @dmahugh

Internal bug: 166293186

2) Did someone already solve this?
The workaround is to enable retries doing the following:

```javascript
// Imports the Google Cloud client library
const {Storage} = require('@google-cloud/storage');

// Your Google Cloud Platform project ID
const projectId = 'project-id';

// Creates a client
const storage = new Storage({
  projectId: projectId,
});

// The name for the new bucket
const bucketName = 'bucket-name';
const contents = 'This is the contents of the file.';

storage
  .bucket(bucketName)
  .file('test')
  .save(contents, {
      autoRetry: true, // <<-- required to enable retries for multipart.
      resumable: false, // means, use multipart upload instead of resumable upload.
      }, function(err) {
    if (!err) {
      // File written successfully.
      console.log("File was written!");
    }
  });
```

#### Environment details

  - Node.js version: 12.7.0
  - `@google-cloud/storage` version: 5.3.0

### PR DESCRIPTION
**Pull request by shaffeeullah**
Fixes https://github.com/googleapis/nodejs-storage/issues/1281 🦕

### CODE REVIEW

File: src/file.ts [hunk 1]
```diff
@@ -3560,15 +3564,31 @@ class File extends ServiceObject<File> {
...
     const options =
       typeof optionsOrCallback === 'object' ? optionsOrCallback : {};
-
-    const writable = this.createWriteStream(options)
-      .on('error', callback!)
-      .on('finish', callback!);
-    if (options.onUploadProgress) {
-      writable.on('progress', options.onUploadProgress);
+    const isMultipart = options.resumable === false;
+    const returnValue = retry(async (bail: (err: Error) => void) => {
```
Comment (frankyn) [inline src/file.ts:3568]: This is a future todo: How can retry config be uniform between this retry logic versus what's in nodejs-common repo?

File: src/file.ts [hunk 2]
```diff
@@ -3816,7 +3836,7 @@ class File extends ServiceObject<File> {
  * that a callback is omitted.
  */
 promisifyAll(File, {
-  exclude: ['publicUrl', 'request', 'setEncryptionKey'],
+  exclude: ['publicUrl', 'request', 'save', 'setEncryptionKey'],
```
Comment (frankyn) [inline src/file.ts:3839]: is this considered a breaking change?

File: test/file.ts [hunk 3]
```diff
@@ -3853,6 +3865,151 @@ describe('File', () => {
...
+        };
+        await file.save(BUFFER_DATA, options);
+        assert.strictEqual(streamFinished, true);
+      });
+
+      it('buffer upload should retry on first failure', async () => {
+        const options = {resumable: false};
+        let retryCount = 0;
+        file.createWriteStream = (options_: {}) => {
+          class DelayedStream extends Transform {
```
Comment (frankyn) [inline test/file.ts:3935]: Can you make this a test helper class that can be deduped for each use-case?

**Review by frankyn — CHANGES_REQUESTED** [review]

File: src/file.ts (hunk 2 above)
Comment (shaffeeullah) [reply src/file.ts:3839]: It is not. Instead of `save` being promisified here at the end, it is promisified in the function itself.

File: src/file.ts [hunk 4]
```diff
@@ -3517,6 +3519,8 @@ class File extends ServiceObject<File> {
    * Resumable uploads are automatically enabled and must be shut off explicitly
    * by setting `options.resumable` to `false`.
    *
+   * Multipart uploads with retryable error codes will be retried 10 times with exponential backoff.
+   *
    * <p class="notice">
    *   There is some overhead when using a resumable upload that can cause
```
Comment (tritone) [inline src/file.ts:3525]: Out of curiosity, is this true? The node library doesn't automatically choose multipart for small files?

File: src/file.ts [hunk 5]
```diff
@@ -3517,6 +3519,8 @@ class File extends ServiceObject<File> {
    * Resumable uploads are automatically enabled and must be shut off explicitly
    * by setting `options.resumable` to `false`.
    *
+   * Multipart uploads with retryable error codes will be retried 10 times with exponential backoff.
```
Comment (tritone) [inline src/file.ts:3522]: Do resumable uploads not retry currently? If they do, probably good to add docs about both.

File: src/file.ts [hunk 6]
```diff
@@ -3560,15 +3564,31 @@ class File extends ServiceObject<File> {
...
-
-    const writable = this.createWriteStream(options)
-      .on('error', callback!)
-      .on('finish', callback!);
-    if (options.onUploadProgress) {
-      writable.on('progress', options.onUploadProgress);
+    const isMultipart = options.resumable === false;
+    const returnValue = retry(async (bail: (err: Error) => void) => {
+      await new Promise<void>((resolve, reject) => {
+        const writable = this.createWriteStream(options)
```
Comment (tritone) [inline src/file.ts:3570]: Do end users ever use streams directly, or is it more typical to use save?

File: src/file.ts (hunk 4 above)
Comment (frankyn) [reply src/file.ts:3525]: It does not have a short circuit on that. It depends on a config option named `resumable` to be set to false for a multipart. By default it's always true (resumable)

File: src/file.ts (hunk 6 above)
Comment (frankyn) [reply src/file.ts:3570]: That's the open question raised in today's meeting. We aren't sure. It might not a use-case for `file.save()` and @shaffeeullah is looking into it.

File: src/file.ts [hunk 7]
```diff
@@ -3587,7 +3587,7 @@ class File extends ServiceObject<File> {
     if (!callback) {
       return returnValue;
     } else {
-      return returnValue.then(callback);
+      return returnValue.then(callback).catch(callback);
```
Comment (frankyn) [inline src/file.ts:3590]: This looks wrong, but I'm not sure. Should there be two different values for `then()` and `catch()`?

Comment (bcoe) [reply src/file.ts:3590]: The first argument to the closure passed to `catch` will be `err` if it's invoked, the `then` in this case will be invoked with no arguments. So, I believe this behavior works as expected `callback()` when there's a success `callback(err)` on failure.

We should make sure there's a test.

File: src/file.ts (hunk 1 above)
Comment (shaffeeullah) [reply src/file.ts:3568]: Which logic in `nodejs-common` are you referring to here?

File: src/file.ts (hunk 7 above)
Comment (shaffeeullah) [reply src/file.ts:3590]: @bcoe I believe the error case is already covered by [this system test ](https://github.com/googleapis/nodejs-storage/blob/1d0a7a6aa1c016cc73da2088c083ca571d7aebd9/system-test/storage.ts#L1493) as well as [this unit test](https://github.com/googleapis/nodejs-storage/blob/1d0a7a6aa1c016cc73da2088c083ca571d7aebd9/test/file.ts#L3979). The success case is covered by multiple tests such as [this one ](https://github.com/googleapis/nodejs-storage/blob/1d0a7a6aa1c016cc73da2088c083ca571d7aebd9/test/file.ts#L3944). Is there another method of testing this that you envision?

File: src/file.ts (hunk 1 above)
Comment (frankyn) [reply src/file.ts:3568]: I was referring to [autoRetry and maxRetries](https://github.com/googleapis/nodejs-common/blob/611d16ba465b53d5eeb3ad59d37a2501a77c3b87/src/util.ts#L118-L134) options.

**Review by frankyn — APPROVED** [review]
LGTM!

File: src/file.ts (hunk 5 above)
Comment (shaffeeullah) [reply src/file.ts:3522]: @frankyn Do you know if there is existing documentation on resumable upload retries? I'm struggling to find it. @tritone, good callout for adding this documentation, but I'm not sure it belongs here. Multipart retries happen in this function (`file.save`), so it is documented on the function. If resumable upload retries happen, they happen in another function.

File: src/file.ts (hunk 6 above)
Comment (shaffeeullah) [reply src/file.ts:3570]: PR here: https://github.com/googleapis/nodejs-storage/pull/1388

File: src/file.ts (hunk 1 above)
Comment (shaffeeullah) [reply src/file.ts:3568]: If I understand correctly, this logic is retrying certain requests. What we're doing here is retrying all the logic, not just the request. I believe that in order to do something similar, we'll have to refactor `File.save` so it passes `data` to `File.createWriteStream`. Then, on request failure, we can do a similar retry.

File: src/file.ts [hunk 8]
```diff
@@ -64,6 +64,8 @@ import {
 const duplexify: DuplexifyConstructor = require('duplexify');
 import {normalize, objectKeyToLowercase, unicodeJSONStringify} from './util';
 import {GaxiosError, Headers, request as gaxiosRequest} from 'gaxios';
+// eslint-disable-next-line @typescript-eslint/no-var-requires
```
Comment (bcoe) [inline src/file.ts:67]: It would be worth figuring out how to use this library with an `import`.

Did we try:

```
import retry from 'async-retry'
```

File: test/file.ts [hunk 9]
```diff
@@ -3853,6 +3865,129 @@ describe('File', () => {
 
   describe('save', () => {
     const DATA = 'Data!';
+    const BUFFER_DATA = Buffer.from(DATA, 'utf8');
+
+    class DelayedStreamNoError extends Transform {
+      _transform(chunk: any, _encoding: string, done: Function) {
```
Comment (bcoe) [inline test/file.ts:3871]: might b e worth giving chunk a type, I believe it will be a `Buffer` or `string`.

File: test/file.ts [hunk 10]
```diff
@@ -3853,6 +3865,129 @@ describe('File', () => {
...
+          return new DelayedStream500Error(retryCount);
+        };
+        await file.save(BUFFER_DATA, options);
+        assert.ok(retryCount === 2);
+      });
+
+      it('non-multipart upload should not retry', async () => {
+        const options = {resumable: true};
+        let retryCount = 0;
+        file.createWriteStream = (options_: {}) => {
```
Comment (bcoe) [inline test/file.ts:3966]: Can you just get rid of the `option_` if you're not using it? alternatively putting a leading `_` rather than trailing `_` might satisfy the linter.

**Review by bcoe — APPROVED** [review]

**Review by frankyn — APPROVED** [review]
