### PR TITLE
Fixes getSignedUrl Return Type

### LINKED ISSUE #497: getSignedUrl response type is wrong
node 8.12
npm 6.4.1
@google-cloud/storage 2.2

The `getSignedUrl` signature looks like:

`getSignedUrl(cfg: GetSignedUrlConfig): Promise<GetSignedPolicyResponse>`

It should be:

`getSignedUrl(cfg: GetSignedUrlConfig): Promise<GetSignedUrlResponse>`

This is according to the documentation:

`* @returns {Promise<GetSignedUrlResponse>}`

### PR DESCRIPTION
**Pull request by reichjustin**
Fixes #497 

Currently, the getSignedUrl type is returning GetSignedPolicyResponse. It should be GetSignedUrlResponse

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by reichjustin** [comment]
I Agreed

File: src/file.ts [hunk 1]
```diff
@@ -2311,7 +2311,7 @@ class File extends ServiceObject {
    * region_tag:storage_generate_signed_url
    * Another example:
    */
-  getSignedUrl(cfg: GetSignedUrlConfig): Promise<GetSignedPolicyResponse>;
+  getSignedUrl(cfg: GetSignedUrlConfig): Promise<GetSignedUrlResponse>;
   getSignedUrl(cfg: GetSignedUrlConfig, callback: GetSignedUrlCallback): void;
   getSignedUrl(cfg: GetSignedUrlConfig, callback?: GetSignedUrlCallback):
       void|Promise<GetSignedPolicyResponse> {
```
Comment (JustinBeckwith) [inline src/file.ts]: Thanks for the PR! Can you update this as well?

**Comment by JustinBeckwith** [comment]
Thank you so much for the fix!
