### PR TITLE
fix: use correct indices for file.from and fix tests to verify names

### LINKED ISSUE #2448: File.from picks up incorrect bucket name from passed URL
I'm going crazy here, as I'm exactly replicating the test case: https://github.com/googleapis/nodejs-storage/pull/2432/files#diff-84c67ae7b647502a4aa36d73e488640768b074793ad0b8c940a22af156e96f0b
And there it worked.

The test also did run: https://github.com/googleapis/nodejs-storage/actions/runs/8440365167/job/23117068589?pr=2432#step:8:689
image

Though for me the bucket name is always `gs` ...

When running the regex in the browser it is clear why the issue exists:
image
The bucket name is at index `[0][2]` but [here](https://github.com/googleapis/nodejs-storage/pull/2432/files#diff-bc9705d0f7a567399044dfc66ccc82d4d9aa1cff116842a0094d54e463c9ecbcR2381) it's accessed by index `[0][1]`

(though I don't understand why the test wouldn't have caught it)

#### Environment details

  - OS: macOS
  - Node.js version: `v20.11.0`
  - npm version: `10.2.4`
  - `@google-cloud/storage` version: `7.10.1`

#### Steps to reproduce

  1. Run `npx gts init` (use defaults)
  2. Run `npm i @google-cloud/storage`
  3. Run `npm i ts-node`
  4. Add the following script: `"start": "ts-node ./src/index.ts",`
  5. Change the `src/index.ts` to:
```ts
import {Storage, File} from '@google-cloud/storage';

const file = File.from(
  'gs://mybucket/myfile',
  new Storage({
    projectId: 'simpleclub',
  })
);
console.log(file.bucket.name); // 'gs'
````
6. Run using `npm run start`

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by ddelgrosso1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2448 🦕

### CODE REVIEW

File: test/file.ts [hunk 1]
```diff
@@ -5180,26 +5180,26 @@ describe('File', () => {
...
+      assert.strictEqual(result.bucket.name, 'mybucket');
+      assert.strictEqual(result.name, 'myfile');
     });
 
     it('should create a File object from a gs:// formatted URL including a folder', () => {
       const gsUrl = 'gs://mybucket/myfolder/myfile';
       const result = File.from(gsUrl, STORAGE);
 
       assert(result);
-      assert(result.bucket.name, 'mybucket');
```
Comment (danielbankhead) [inline test/file.ts:5192]: Yea, the `assert` with 2 params gets me too at times.

**Review by danielbankhead — APPROVED** [review]

File: test/file.ts (hunk 1 above)
Comment (danielbankhead) [reply test/file.ts:5192]: Where the ‘mybucket’ here is treated as the error message
