### PR TITLE
test: add delay to metadata updates in bucket kms tests

### LINKED ISSUE #2228: storage write, read, and remove files kms keys buckets: should insert an object that inherits the kms key name failed
Note: #2209 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 37ce0a67748b66d3d7f4f94a12d416b725a3f30a
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/38249289-7027-4b33-800c-f2c34d2b6a53), [Sponge](http://sponge2/38249289-7027-4b33-800c-f2c34d2b6a53)
status: failed
<details><summary>Test output</summary><br><pre>Expected values to be strictly equal:
+ actual - expected

+ undefined
- 'projects/long-door-651/locations/us/keyRings/storage-tests-400c81c0-400e7d90/cryptoKeys/storage-tests-400c81c0-400e7d91/cryptoKeyVersions/1'
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ undefined
- 'projects/long-door-651/locations/us/keyRings/storage-tests-400c81c0-400e7d90/cryptoKeys/storage-tests-400c81c0-400e7d91/cryptoKeyVersions/1'
    at Context.<anonymous> (build/system-test/storage.js:2041:28)
        -> /workspace/system-test/storage.ts:2599:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre></details>

### PR DESCRIPTION
**Pull request by ddelgrosso1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2228  🦕

### CODE REVIEW

File: system-test/storage.ts [hunk 1]
```diff
@@ -59,6 +59,7 @@ const RUNNING_IN_VPCSC = !!process.env['GOOGLE_CLOUD_TESTS_IN_VPCSC'];
 
 const UNIFORM_ACCESS_TIMEOUT = 60 * 1000; // 60s see: https://cloud.google.com/storage/docs/consistency#eventually_consistent_operations
 const UNIFORM_ACCESS_WAIT_TIME = 5 * 1000; // 5s
+const BUCKET_METADATA_UPDATE_WAIT_TIME = 1000; // 1s
```
Comment (danielbankhead) [inline system-test/storage.ts:62]: Maybe a comment here for future us/team describing the issue

**Review by danielbankhead — APPROVED** [review]
Looks good, one optional comment
