### PR TITLE
test: increase timeout of delay in hmac get test

### LINKED ISSUE #2456: storage HMAC keys: should get metadata for an HMAC key failed
Note: #2415 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 13e29f768e41565346504fde4693ddddbb2cef2a
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/83ff0515-6902-4c20-9eb2-051ea8c2c33d), [Sponge](http://sponge2/83ff0515-6902-4c20-9eb2-051ea8c2c33d)
status: failed

### PR DESCRIPTION
**Pull request by ddelgrosso1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2456 🦕

### CODE REVIEW

File: system-test/storage.ts [hunk 1]
```diff
@@ -3110,7 +3109,6 @@ describe('storage', function () {
     });
 
     it('should get metadata for an HMAC key', async function () {
-      this.retries(3);
```
Comment (ddelgrosso1) [inline system-test/storage.ts:3113]: This is no longer necessary as `this.retries(3)` is set at the outermost level.

**Review by danielduhh — COMMENTED** [review]
Im guessing this issue exists in other languages. What are other folks doing to mitigate this?

**Comment by ddelgrosso1** [comment]
@danielduhh added https://github.com/googleapis/nodejs-storage/issues/2461

**Review by danielduhh — APPROVED** [review]
