### PR TITLE
Fix: improve GetFilesResponse interface

### LINKED ISSUE #2464: Missing interface's property
Why doesn't the second element of the array have the property pageToken?
https://github.com/googleapis/nodejs-storage/blob/b4dbd73189b9fae4c23d614753670ee562bc717b/src/bucket.ts#L90
Screenshot 2024-05-12 at 21 11 41

 This property will be present if you pass `{ autoPaginate: false }` into `Storage.getFiles`.

### PR DESCRIPTION
**Pull request by olishevskii**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes https://github.com/googleapis/nodejs-storage/issues/2464 🦕

### CODE REVIEW

**Comment by ddelgrosso1** [comment]
Hi @olishevskii thank you for opening a PR and trying to clean this up. 

If you take a look at https://github.com/googleapis/nodejs-storage/blob/b4dbd73189b9fae4c23d614753670ee562bc717b/src/bucket.ts#L2840 you will see that what is actually being returned is a cross between `GetFilesOptions & {pageToken?: string}`. This PR omits the `GetFilesOptions` portion. 

I'm also not sure we want to define a new interface that will need to be exported just to hold the page token portion.

**Comment by olishevskii** [comment]
Hi @ddelgrosso1. I see your point of view regarding defining a new interface `NextPageFilesOptions`. I've rewritten my solution using TypeScript utilities. Additionally, I noticed that a query can be not only like `GetFilesOptions` but also like `GetFilesCallback`.
https://github.com/googleapis/nodejs-storage/blob/b4dbd73189b9fae4c23d614753670ee562bc717b/src/bucket.ts#L2798-L2802

File: src/bucket.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ interface MetadataOptions {
   ifMetagenerationNotMatch?: number | string;
 }
 
-export type GetFilesResponse = [File[], {}, unknown];
+export type GetFilesResponse = [File[], (GetFilesOptions | GetFilesCallback) & Partial<Pick<GetFilesOptions, 'pageToken'>>, unknown];
```
Comment (ddelgrosso1) [inline src/bucket.ts:90]: You can omit `GetFilesCallback`, `query` can only be `GetFilesOptions` or an empty object. It will never get assigned the callback.

Comment (olishevskii) [reply src/bucket.ts]: I fixed it.

**Review by ddelgrosso1 — APPROVED** [review]
