### PR TITLE
fix: make sure destination uses posix separator instead of win

### LINKED ISSUE #2301: uploadManyFiles prefix option  turns forward slash to backward slash on windows, turning folders into full string file name, is this intended?
#### Environment details

  - OS: Windows 10
  - Node.js version: 18.17.1
  - npm version: 9.6.7
  - `@google-cloud/storage` version: ^6.11.0

#### Steps to reproduce

```javascript
        const files_to_upload = [
            "images/image001.png",
            "images/image002.jpg",
        ]

        await tsfm.uploadManyFiles(files_to_upload, {
            prefix:"user_id_1/files",
            passthroughOptions: {
                gzip: true,
            }
        })
```
the code above will upload the files with the prefix and path as it's entire file name:

- user_id_1\files\images\image001.png
- user_id_1\files\images\image002.jpg

in turn making the url show up as
- `https://storage.googleapis.com/example_bucket/user_id_1%5Cfiles%5Cimages%5Cimage001.png`
- `https://storage.googleapis.com/example_bucket/user_id_1%5Cfiles%5Cimages%image002.jpg`

expecting it to correctly create directory such as:
- `https://storage.googleapis.com/example_bucket/user_id_1/files/images/image001.png`
- `https://storage.googleapis.com/example_bucket/user_id_1/files/images/image002.jpg`

only happens on windows machine, [suspecting `path.join` function on the `uploadManyFiles`](https://github.com/googleapis/nodejs-storage/blob/da3462b0ffa66f5474c2bf8c4f1c95cceb33ce95/src/transfer-manager.ts#L401), is this intended?

removing the `prefix` options correctly uploads it into a directory as expected:
- `https://storage.googleapis.com/example_bucket/images/image001.png`
- `https://storage.googleapis.com/example_bucket/images/image002.jpg`

### PR DESCRIPTION
**Pull request by ddelgrosso1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2301  🦕

### CODE REVIEW

File: src/transfer-manager.ts [hunk 1]
```diff
@@ -396,12 +396,14 @@ export class TransferManager {
         ...options.passthroughOptions,
       };
 
-      passThroughOptionsCopy.destination = filePath;
+      passThroughOptionsCopy.destination = filePath
+        .split(path.win32.sep)
```
Comment (danielbankhead) [inline src/transfer-manager.ts:400]: Perhaps using the OS-specific `path.sep` would be preferred to prefer POSIX customers' ability to write with `\`.

```suggestion
        .split(path.sep)
```

File: src/transfer-manager.ts [hunk 2]
```diff
@@ -396,12 +396,14 @@ export class TransferManager {
...
+        .join(path.posix.sep);
       if (options.prefix) {
-        passThroughOptionsCopy.destination = path.join(
-          options.prefix,
-          passThroughOptionsCopy.destination
-        );
+        passThroughOptionsCopy.destination = path
+          .join(options.prefix, passThroughOptionsCopy.destination)
+          .split(path.win32.sep)
+          .join(path.posix.sep);
```
Comment (danielbankhead) [inline src/transfer-manager.ts:406]: Maybe the prefix here should be split first to preserve the `\` for POSIX (in case customers really want it)

```suggestion
          .posix.join(...options.prefix.split(path.sep), passThroughOptionsCopy.destination);
```

**Review by danielbankhead — APPROVED** [review]
