### PR TITLE
fix: Remove `pumpify`

### LINKED ISSUE #1915: refactor(deps): Remove `pumpify` dependency
Native [streams](https://nodejs.org/api/stream.html) should suffice.

### PR DESCRIPTION
**Pull request by danielbankhead**
Fixes #1915 🦕

As a follow-up, we should remove [`duplexify`](https://github.com/mafintosh/duplexify), which is a breaking change as it is exposed as a return type in a few places. In many places, a `Transform` stream makes more sense and is much cleaner.

### CODE REVIEW

File: src/file.ts [hunk 1]
```diff
@@ -1948,101 +1950,92 @@ class File extends ServiceObject<File> {
...
     }
 
-    // Collect data as it comes in to store in a hash. This is compared to the
-    // checksum value on the returned metadata from the API.
-    const validateStream = new HashStreamValidator({
+    /**
+     * A callback for determining when the underlying pipeline is complete.
+     * It's possible the pipeline callback could error before the write stream
+     * calls `final` so by default this will destroy the write stream unless the
+     * write stream sets this callback via it's `final` handler.
```
Comment (shaffeeullah) [inline src/file.ts:1957]: nit: `its`

**Review by shaffeeullah — APPROVED** [review]
one small nit, but otherwise looks good! please wait for @ddelgrosso1 to take a look as well. thanks for doing this!!

**Comment by ddelgrosso1** [comment]
Overall nothing stands out to me as troublesome. Perhaps we should move this to a fix and/or feature. We have handled quite a few things during this fixit week and it might be nice to do a release.
