### PR TITLE
fix: correctly handle an empty file in download function

### LINKED ISSUE #1991: Download method hangs on zero byte files
#### Environment details

  - OS: Mac OS 12.4
  - Node.js version: 14.18.2
  - npm version: 6.14.15
  - `@google-cloud/storage` version: 6.1.0

#### Steps to reproduce

  1.  Create an empty file (e.g. `touch emptyfile.txt`) and upload it to cloud storage.
  2. Download the file using the code below

```
const storage = new Storage({ retryOptions: { autoRetry: false } });
storage
  .bucket(BUCKET_NAME)
  .file(emptyfile)
  .download({ destination: destFilename })
  .then(() => console.log("Success"))
  .catch(() => console.error("Error"));
```

When the target file has a size of zero bytes, the promise gets stuck in the pending state. It never resolves or throws an error. If using the method as async rather than a promise then the next line will never get called.

From what I can tell, changing the `autoRetry` options don't seem to make any difference.

Thanks,

Pete

### PR DESCRIPTION
**Pull request by ddelgrosso1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1991  🦕

### CODE REVIEW

File: test/file.ts [hunk 1]
```diff
@@ -55,6 +55,7 @@ import {
 } from '../src/file';
 import {ExceptionMessages, IdempotencyStrategy} from '../src/storage';
 import {formatAsUTCISO} from '../src/util';
+import {timeStamp} from 'console';
```
Comment (shaffeeullah) [inline test/file.ts:58]: remove unused variable

**Review by shaffeeullah — APPROVED** [review]
looks good other than the extra line. thanks, denis!!

File: test/file.ts (hunk 1 above)
Comment (ddelgrosso1) [reply test/file.ts]: When tab autocomplete goes wrong...

File: src/file.ts [hunk 2]
```diff
@@ -2043,14 +2043,27 @@ class File extends ServiceObject<File> {
...
-
+    let receivedData = false;
     if (destination) {
-      fileStream.on('error', callback).once('data', data => {
-        // We know that the file exists the server - now we can truncate/write to a file
-        const writable = fs.createWriteStream(destination);
-        writable.write(data);
-        fileStream.pipe(writable).on('error', callback).on('finish', callback);
-      });
+      fileStream
```
Comment (danielbankhead) [inline src/file.ts:2048]: [Optional]: Now we're on Node 12+ we can use `for await (const chunk of readable)` to make this tinier: https://nodejs.org/api/stream.html#readablesymbolasynciterator

**Review by danielbankhead — APPROVED** [review]
LGTM, one optional comment

File: src/file.ts (hunk 2 above)
Comment (ddelgrosso1) [reply src/file.ts:2048]: Since this isn't within an async function currently I'm going to leave it alone for the time being until we modernize our function signatures.
