### PR TITLE
fix: `File#save` iterable fixes

### LINKED ISSUE #2278: storage file generations: "after all" hook for "should throw an error Precondition Failed on overwrite with version 0, then save file with and without resumable" failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: e0f45c24b44d11c72ff40cc534be11cb2a65192f
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/7a8225b6-9803-40e1-af9d-b2d612b30435), [Sponge](http://sponge2/7a8225b6-9803-40e1-af9d-b2d612b30435)
status: failed
<details><summary>Test output</summary><br><pre>The bucket you tried to delete is not empty.
Error: The bucket you tried to delete is not empty.
    at new ApiError (build/src/nodejs-common/util.js:79:15)
    at Util.parseHttpRespBody (build/src/nodejs-common/util.js:218:38)
    at Util.handleResp (build/src/nodejs-common/util.js:158:30)
    at /workspace/build/src/nodejs-common/util.js:548:22
    at onResponse (node_modules/retry-request/index.js:240:7)
    at null.<anonymous> (node_modules/teeny-request/src/index.ts:333:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)</pre></details>

### PR DESCRIPTION
**Pull request by danielbankhead**
Fixes #2278 🦕

### CODE REVIEW

File: src/file.ts [hunk 1]
```diff
@@ -3644,20 +3643,6 @@ class File extends ServiceObject<File, FileMetadata> {
     }
     const returnValue = retry(
       async (bail: (err: Error) => void) => {
-        if (data instanceof Readable) {
```
Comment (danielbankhead) [inline src/file.ts:3647]: Removing this logic as for the vast majority it would simply slow down their uploads unnecessarily. Additionally, later versions of Node.js catch this for us.

File: test/file.ts [hunk 2]
```diff
@@ -4439,33 +4414,6 @@ describe('File', () => {
...
-        };
-
-        const generator = async function* () {
-          yield {thisIsNot: 'a buffer or a string'};
-        };
-
-        file.save(generator(), options, (err: Error) => {
-          assert.strictEqual(
-            err.message,
-            'The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object'
```
Comment (danielbankhead) [inline test/file.ts:4463]: This is just testing Node internals. Removed.

File: src/file.ts (hunk 1 above)
Comment (ddelgrosso1) [reply src/file.ts:3647]: Do you know what versions catch this?

**Review by ddelgrosso1 — APPROVED** [review]

File: src/file.ts (hunk 1 above)
Comment (danielbankhead) [reply src/file.ts:3647]: Node 18.0.0:
- https://github.com/nodejs/node/pull/46600
- https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.0.0

Here's a simple reproduction for a REPL (anything before 18 the `console.log` isn't called):
```
const readable = stream.Readable({read() {this.push(null)}});
readable.read();
readable.readable // false
stream.pipeline(readable, stream.PassThrough, () => console.log('done'));
```

File: src/file.ts [hunk 3]
```diff
@@ -3687,17 +3672,10 @@ class File extends ServiceObject<File, FileMetadata> {
           } else {
             pipeline(data, writable, err => {
               if (err) {
-                // If data is not a valid PipelineSource, then pipeline will
-                // fail without destroying the writable stream. If data is a
-                // PipelineSource that yields invalid chunks (e.g. a stream in
-                // object mode or an iterable that does not yield Buffers or
-                // strings), then pipeline will destroy the writable stream.
-                if (!writable.destroyed) writable.destroy();
```
Comment (danielbankhead) [inline src/file.ts:3695]: This case doesn't happen - instead, Node throws immediately and this callback is never called.
