### PR TITLE
test: allow environmentally-conditional errors

### LINKED ISSUE #1105: Mocha Tests: should not upload a file failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

buildID: 6833dfe9bf013a582ff46620b8035fc47ec38d0f
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/23576859-39e5-431f-8d1c-4d246dcac16a), [Sponge](http://sponge2/23576859-39e5-431f-8d1c-4d246dcac16a)
status: failed

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #1105 

We've been getting a different (expected) error message on Kokoro vs local development environments. This allows either one to pass the test.

### CODE REVIEW

File: bin/benchwrapper.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ function read(call, callback) {
     .bucket(bucketName)
     .file(objectName)
     .download({validation: false})
-    .then(() => callback(null, null))
+    .then(() => callback(null, null));
```
Comment (stephenplusplus) [inline bin/benchwrapper.js]: npm run fix was here.

**Comment by jkwlui** [comment]
Looks like sometimes the compute engine default credential is available to the library and sometimes it's not.
