### PR TITLE
fix: retry uri creation dep update & conformance tests

### LINKED ISSUE #1703: storage requester pays existing bucket methods that accept userProject: file#createResumableUpload failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 4dc24a0bf9f1509a26e74d46c2613a971585620d
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/b06869bd-da76-4370-95dd-0a8c8f260a09), [Sponge](http://sponge2/b06869bd-da76-4370-95dd-0a8c8f260a09)
status: failed
<details><summary>Test output</summary><br><pre>Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/workspace/build/system-test/storage.js)
Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/workspace/build/system-test/storage.js)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)</pre></details>

### PR DESCRIPTION
**Pull request by shaffeeullah**
Dependent on https://github.com/googleapis/gcs-resumable-upload/pull/475 merged and upgrading dependency version

Fixes https://github.com/googleapis/nodejs-storage/issues/1703

### CODE REVIEW

**Review by ddelgrosso1 — APPROVED** [review]

**Review by ddelgrosso1 — APPROVED** [review]

File: src/storage.ts [hunk 1]
```diff
@@ -265,7 +265,7 @@ const RETRYABLE_ERR_FN_DEFAULT = function (err?: ApiError) {
 
     if (err.errors) {
       for (const e of err.errors) {
-        const reason = e?.reason?.toLowerCase();
+        const reason = e?.reason?.toString().toLowerCase();
```
Comment (shaffeeullah) [inline src/storage.ts:268]: @ddelgrosso1 not sure why `as string` in the gcs-resumable-upload library didn't work, but this should fix it. I think this is a good change to have in our function anyway because it makes our function safer. I will update the resumable library as well, but this should unblock us for now.

**Review by ddelgrosso1 — APPROVED** [review]
