### PR TITLE
fix: remove async from final function which causes double invocation …

### LINKED ISSUE #2082: ERR_MULTIPLE_CALLBACK on file.download()
1) Is this a client library issue or a product issue?
yes

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-storage/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
no

3) Do you have a support contract?
no

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Win10 21H2
  - Node.js version: 16.13.2
  - npm version: 8.1.2
  - `@google-cloud/storage` version: 6.5.2

#### Steps to reproduce

  Try to download a file:
```
  try {
    await file.download({
      destination: destination
    })
  } catch(e) {
    console.log(e);
  }
```

As the result catching error ERR_MULTIPLE_CALLBACK

### PR DESCRIPTION
**Pull request by ddelgrosso1**
…of callback

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2082 🦕

### CODE REVIEW

**Comment by ddelgrosso1** [comment]
I believe this is related to https://github.com/nodejs/node/issues/39535 which can cause double invocation of callbacks under the same situation we had in the code here.

**Review by danielbankhead — APPROVED** [review]

File: src/file.ts [hunk 1]
```diff
@@ -1530,12 +1530,15 @@ class File extends ServiceObject<File> {
...
             // Preserving `onComplete`'s ability to
             // destroy `throughStream` before pipeline
             // attempts to.
-            await onComplete(null);
-            cb();
+            onComplete(null)
+              .then(() => {
+                cb();
+              })
+              .catch(cb);
```
Comment (julienw) [inline src/file.ts:1541]: couldn't this cause a double invocation if `cb` throws?

I think I would have used something such as:
```
.then(
  () => cb(),
  () => cb()
)
```

Also I'm not entirely sure how the previous code would end up with a double invocation, but I may miss some context.
