### PR TITLE
fix: revert skip validation

### LINKED ISSUE #709: CONTENT_DOWNLOAD_MISMATCH with successful file download
#### Environment details
* OS: Windows 10 Pro 1809
* Node.js version: v10.15.3 LTS
* npm version: 6.4.1
* `@google-cloud/storage` version: 2.5.0

#### Steps to reproduce
0. Prepare a bucket with Cloud KMS Customer managed Key encryption. All files are private.
1. Upload an JPEG image file using: 
```javascript
function UploadFile() {
    storage.bucket("somebucket").upload("somefolder/someimage.jpg", {
        gzip: true,
        destination: "somefolder/someimage.jpg",
    }).then(results => {
        console.log("upload OK");
    })
    .catch(err => {
        console.error("Error: ", err);
    });
}
UploadFile()
// Upload works fine.
```
2. Try downloading the img file using: 
```javascript
function DownloadFile() {    
    const file = storage.bucket("somebucket").file("somefolder/someimage.jpg");
    
    file.download({
        destination: "someimage.jpg",
        // validation: false, // Why even disable validation?
    }).then(res => {
        console.log("DL OK");
    }).catch(err => {
        console.error(err); // Throws CONTENT_DOWNLOAD_MISMATCH
    })
}
DownloadFile()
```
3. ***Correct decompressed file is downloaded*** AND exception is thrown: `code=CONTENT_DOWNLOAD_MISMATCH message=The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again.`

I've read through [Issue 566](https://github.com/googleapis/nodejs-storage/issues/566), but seems like not a solution.

`storage.bucket("somebucket").file("somefolder/someimage.jpg").download({validation: false});` works, but there's no reason to or should disable validation.

To make sure if the hashes are actually a mismatch, I ran a local md5sum check on the downloaded and original image files.

```
$ md5sum downloaded.jpg original.jpg
a045a2e8e6b8d84aa8a319bcdba05419  downloaded.jpg
a045a2e8e6b8d84aa8a319bcdba05419  original.jpg
```

Downloaded file is a match to the original file.

BTW, This problem doesn't happen if the image is not gzipped on upload.

Thanks

### PR DESCRIPTION
**Pull request by shaffeeullah**
Fixes https://github.com/googleapis/nodejs-storage/issues/709

### CODE REVIEW

File: src/file.ts [hunk 1]
```diff
@@ -1536,23 +1536,17 @@ class File extends ServiceObject<File> {
...
-        // If object is stored compressed (having
-        // metadata.contentEncoding === 'gzip') and was served decompressed,
-        // then skip checksum validation because the remote checksum is computed
-        // against the compressed version of the object.
-        if (!isServedCompressed) {
+        // Did the server decompress object before serving it back to us?
+        const serverDecompressed =
+          headers['x-goog-stored-content-encoding'] === 'gzip' && !isCompressed;
+
+        if (serverDecompressed) {
```
Comment (frankyn) [inline src/file.ts:1543]: Shoot, I think you need to remove this code block because it's making a secondary get metadata request. This conditional is meant to go around the validation below.

**Review by frankyn — CHANGES_REQUESTED** [review]

File: test/file.ts [hunk 2]
```diff
@@ -1395,19 +1395,6 @@ describe('File', () => {
         };
       }
 
-      describe('server decompression', () => {
-        it('should skip validation if file was stored compressed', done => {
-          file.metadata.crc32c = '.invalid.';
```
Comment (frankyn) [inline test/file.ts:1400]: i think this is still needed no?

**Review by frankyn — COMMENTED** [review]
One more comment.

File: system-test/storage.ts [hunk 3]
```diff
@@ -2516,33 +2516,6 @@ describe('storage', () => {
...
-              undefined
-            );
-          })
-          .pipe(fs.createWriteStream(tmpFilePath))
-          .on('error', reject)
-          .on('finish', resolve);
-      });
-
-      await file.delete();
-    });
```
Comment (danielbankhead) [inline system-test/storage.ts:2544]: I think the opposite of this test should exist

Comment (shaffeeullah) [reply system-test/storage.ts]: this test is actually still needed. i had misunderstood the implementation

**Comment by shaffeeullah** [comment]
@frankyn i think this system test is failing because it's not returning the `'x-goog-stored-content-encoding'` header. is that supposed to happen automatically?

**Review by danielbankhead — CHANGES_REQUESTED** [review]
I think we need some integration tests to associate with the new behavior

File: src/file.ts [hunk 4]
```diff
@@ -1536,31 +1536,16 @@ class File extends ServiceObject<File> {
...
+        const serverDecompressed =
+          headers['x-goog-stored-content-encoding'] === 'gzip' && !isCompressed;
 
         // If we're doing validation, assume the worst-- a data integrity
         // mismatch. If not, these tests won't be performed, and we can assume
         // the best.
         let failed = crc32c || md5;
 
-        if (validateStream) {
+        if (validateStream && !serverDecompressed) {
```
Comment (frankyn) [inline src/file.ts:1548]: Would add a comment detailing why we care about `!serverDecompressed`:

> We must check if the server decompressed the data on serve because hash validation is not possible in this case.

**Review by frankyn — COMMENTED** [review]
One last nit, @shaffeeullah, this will be blocked until the header is no longer allowlist required.

Otherwise, this LGTM! Thank you!

**Comment by shaffeeullah** [comment]
> I think we need some integration tests to associate with the new behavior

There are already integration tests associated with this new boolean.

False case: https://github.com/googleapis/nodejs-storage/blob/0845525a9aebd94da92882ace4cd29bf125641a2/system-test/storage.ts#L2181

True case: https://github.com/googleapis/nodejs-storage/blob/0845525a9aebd94da92882ace4cd29bf125641a2/system-test/storage.ts#L2148

**Comment by shaffeeullah** [comment]
> One last nit, @shaffeeullah, this will be blocked until the header is no longer allowlist required.

What is the timeline for that?

File: src/file.ts [hunk 5]
```diff
@@ -1494,7 +1495,16 @@ class File extends ServiceObject<File> {
...
+        isCompressed = headers['content-encoding'] === 'gzip';
+
+        // The object is safe to validate if:
+        // 1. It was stored gzip and returned to us gzip OR
+        // 2. It was never stored as gzip
+        safeToValidate =
+          (headers['x-goog-stored-content-encoding'] === 'gzip' &&
+            isCompressed) ||
+          headers['x-goog-stored-content-encoding'] === 'identity';
+
```
Comment (danielbankhead) [inline src/file.ts:1507]: Which tests validate the following use cases?
- `headers['x-goog-stored-content-encoding'] === 'gzip' && headers['content-encoding'] === 'gzip'`
- `headers['x-goog-stored-content-encoding'] === 'gzip' && headers['content-encoding'] !== 'gzip'`
- `headers['x-goog-stored-content-encoding'] !== 'gzip' && headers['x-goog-stored-content-encoding'] === 'identity'`

Comment (shaffeeullah) [reply src/file.ts:1507]: Good callout. I was looking at it more like tests for `true` `safeToValidate` and tests for `false` safeToValidate`. I'll add additional tests for the specific situations.

Comment (shaffeeullah) [reply src/file.ts:1507]: @danielbankhead added tests for cases 1 & 2, case 3 is covered by existing tests

File: src/file.ts [hunk 6]
```diff
@@ -1562,31 +1572,13 @@ class File extends ServiceObject<File> {
...
-
         // If we're doing validation, assume the worst-- a data integrity
         // mismatch. If not, these tests won't be performed, and we can assume
         // the best.
-        let failed = crc32c || md5;
-
-        if (validateStream) {
+        // We must check if the server decompressed the data on serve because hash
+        // validation is not possible in this case.
+        let failed = (crc32c || md5) && safeToValidate;
```
Comment (frankyn) [inline src/file.ts:1580]: I think i got confused with `failed` variable; what does it do?

**Review by frankyn — COMMENTED** [review]
One more comment; otherwise LGTM, we can't merge this until the feature is available in production to everyone unless y'all are planning making a release until then.

File: src/file.ts (hunk 6 above)
Comment (shaffeeullah) [reply src/file.ts:1580]: failed defaults to true (if `crc32c || md5`) and then later gets changed to `false` if it passes. (see below lines.) It's not true that it failed if it wasnt `safeToValidate` to begin with, so we need to make sure that's `true` before assuming `failed`

**Review by frankyn — APPROVED** [review]

**Review by danielbankhead — APPROVED** [review]

**Comment by shaffeeullah** [comment]
@frankyn says this is launched, clear to merge
